### ISSUE TITLE
Poor performance with lists

### ISSUE THREAD

**Issue by webdpro** [mac81/pure-drawer#11]
Hi, 

I was trying to use the pure-drawer on a mobile device and I noted that the container classes cause scrolling issues, when I remove the classes the scrolling issue goes away.. I'm using android 4.4, not using overflow scroll but I noticed the container class does make the div a scrolling div but still not sure why that would cause any performance issues with the scroll.. 

Basically the scroll is just really sluggish, like its having a hard time rendering the items on the screen.

I did do a little hack to add / remove classes on click, it works ok, would need some tweaking but would love to not have to hack around it if possible.

Thanks!

**Comment by mac81** [comment]
Hi

Thanks for trying out pure drawer.

I have to test and see if I can reproduce the issue. I will look into it as soon as I can.

**Comment by mac81** [comment]
Are you using Chrome or Android Native browser?

**Comment by webdpro** [comment]
I'm on android 4.4 with wrapper so I'm guessing it's stock and not chromium
browser

**Comment by nward85** [comment]
It does this on iPhone as well. Had to remove container class to fixed scrolling. Now it is very sluggish when scrolling on anything. Any idea how to fix this yet?

**Comment by mac81** [comment]
I've not been able to reproduce the behaviour your describing. But could you try to add style="-webkit-overflow-scrolling: touch;" directly to the .pure-pusher div. It has to be applied inline and not referenced via external css. I think it might fix the issue.

<div class="pure-pusher" style="-webkit-overflow-scrolling: touch;">

**Comment by nward85** [comment]
That worked, even with external css. In your css that style is applied to .pure-container. Remove that and add to .pure-pusher and everything works great.
