### ISSUE TITLE
Fixed navigation with large desktop

### ISSUE THREAD

**Issue by pete45** [mac81/pure-drawer#12]
Thank you for your real awesome navigation.
1. How is it possible to achieve a fixed top navigation with large desktops (i.e. bootstrap lg)?
Regards
Pete

**Comment by mac81** [comment]
Hi there

You want to have the menu as a 'drawer' on smaller screens and visible on large screens? Or did I misinterpreted the question?

Do you use the sass or css version of pure drawer?

**Comment by pete45** [comment]
Hi Thomas,
thank you for your answer.
You are right. On smaller screens as a 'drawer" and on larger screens visible.
I use the sass version 1.01 of pure drawer.
Thanks in advance.
Pete

**Comment by mac81** [comment]
Step 1:
Set the $show-drawer variable in settings.scss to $large-down. Eg. $show-drawer: $large-down; 

Step 2: 
Inside the '@mixin pure-drawer' in pure-drawer-global.scss find the media query '@media {$large-up} {  }'

Step 3: 
Edit your styles inside the media query 

Hope this helps. If you have any further questions please don't hesitate to ask.

**Comment by pete45** [comment]
I tried out the above suggestion with an error result: 
If I follow step 1:
In _pure-drawer_settings.scss line 2 is in download version deactivated. I have activated the line and changed the code from '//$show-drawer: $small-only' to '$show-drawer: $large-down'.
The result is following error message while compiling:
'    error mediwe/css/scss/nav-pure-drawer/pure-drawer.scss (Line 631 of mediwe/css/scss/nav-pure-drawer/pure-drawer/vendor/_animate.scss: You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .bounceInDown" on line 30 of O:/Eigene Dateien/Werbung/Homepage/Templates/Erstes Template/mediwe/css/scss/nav-pure-drawer/pure-drawer/effects/_effect-bounce.scss.
)
Compilation failed in 1 files.'

**Comment by mac81** [comment]
Yup.. An error from my side. I will try and come with an update shortly.

A quick fix will be to move everything inside the @mixin effect-bounce() (Line 6 to 37) and paste it into line 41 and 44 of _effect-bounce.scss

@if($show-drawer == 'all') {
    @include effect-bounce; <----- REPLACE THIS LINE HERE WITH THE CONTENT INSIDE THE MIXIN
} @else {
    @media #{$show-drawer} {
        @include effect-bounce; <----- REPLACE THIS LINE HERE WITH THE CONTENT INSIDE THE MIXIN
    }   
}

**Comment by pete45** [comment]
Thank you for your reply.
Waiting for your update.
In between I´ll try the quick fix and give you a short report when inserted.
Thanks a lot.

**Comment by mac81** [comment]
Disregard my latest quickfix.. It won't work. It's the extend that is causing the issue. 

    [data-effect="pure-effect-bounce"] .pure-drawer[data-position='left'] { @extend .bounceOutLeft; }
    [data-effect="pure-effect-bounce"] .pure-drawer[data-position='right'] { @extend .bounceOutRight; }
    [data-effect="pure-effect-bounce"] .pure-drawer[data-position='top'] { @extend .bounceOutUp; }
    
    [data-effect="pure-effect-bounce"] .pure-toggle[data-toggle='left']:checked ~ .pure-drawer[data-position='left'] { @extend .bounceInLeft; }
    [data-effect="pure-effect-bounce"] .pure-toggle[data-toggle='right']:checked ~ .pure-drawer[data-position='right'] { @extend .bounceInRight; }
    [data-effect="pure-effect-bounce"] .pure-toggle[data-toggle='top']:checked ~ .pure-drawer[data-position='top'] { @extend .bounceInDown; }

You can't have @extend inside a mediaquery.

**Comment by mac81** [comment]
So quickfix would be to replace the extends with the corresponding class in animate.scss

**Comment by Andrewchs** [comment]
Hello there pete45,

Have you achieved that effect? If you could share the working code?

Thanks in advance.

**Comment by pete45** [comment]
Hello Thomas,
I tried to, but aborted, because in my joomla template I discovered another incompatibility between pure-drawer and blueimp gallery. To solve this had priority.
Issue was that all effects with scale (scale down pusher, scale up and scale rotatate pusher) had the effect, that the lightbox of blueimp gallery was not centered on the window. Instead the lightbox was moved down. The problem is caused only by these effects, but I couldn´t solve it either. So I had to disable these effects.
Regards
Pete

**Comment by mac81** [comment]
Is the lightbox markup placed inside the '.pure-pusher-container'? If so I can see this causing an issue because some effects uses perspective and other transform properties.

If you place your lightbox outside of the pure-drawer I don't see this beeing an issue, but I can't be certain without inspecting the code.

**Comment by pete45** [comment]
You are right with the first point:
blueimp gallery is placed inside the '.pure-pusher-container'.
The effects that are using perspectives causing conflicts, so that the lightbox is not centering up the window but the vertical align is centered up the enclosing container.

**Comment by mac81** [comment]
Because the lightbox is inside the .pure-pusher container the lightbox will be affected by perspective. 
If you place it outside this div the lightbo should work. Although it will ofcourse be hidden behind the overlay when the menu is triggered, but that might be what you want.

F.ex. 
<div class="pure-pusher-container">
    <div class="lightbox" style="position: absolute; height: 200px; width: 200px; background: #fff;  z-index: 999;  left: 50%; top: 50%; transform: translate3d(-50%, -50%, 0);"></div>
        <div class="pure-pusher">
