### ISSUE TITLE
Hierarchical Menu

### ISSUE THREAD

**Issue by eliaso** [mac81/pure-drawer#14]
Can you create a hierarchical Menu with the drawers?

**Comment by mac81** [comment]
Could you please specify in more detail what you mean by hierarchical menu?

**Comment by eliaso** [comment]
Thanks!,

 

What I mean is that when you rollover one of the menu items (drawer) that could open on the right side a new menu of Options (like another set of drawers), suppose that one of the main drawers will be Documentation, then when you rollover it it will expand to the side with the new options Documentation-1, Documentation-2, Documentation-3…

 

Like this:

**Comment by mac81** [comment]
Seems like you missed something in the post. An image maybe?

Do you mean something like this?

http://tympanus.net/Development/MultiLevelPushMenu/

**Comment by eliaso** [comment]
Yes, exactly it is also yours?

**Comment by mac81** [comment]
The menu I sendt you is made by Mary Lou. A very talented and skilled web designer and developer over at http://tympanus.net/

This functionality requires the use of Javacript. As of now Pure Drawer is a css only solution. But I might add this functionality if I make a javascript version of Pure Drawer in the future.

You can find the source to the link I sendt you here: http://tympanus.net/codrops/2013/08/13/multi-level-push-menu/

Hopefully it will fit your needs.
