### ISSUE TITLE
firefox toggle doesn't show correctly

### ISSUE THREAD

**Issue by brownprogrammer** [mac81/pure-drawer#15]
Looks great on Chrome, but in Firefox, one slash of the 'X' to close the toggle vanishes. 
![pure-drawer-firefox-png](https://cloud.githubusercontent.com/assets/11048078/7614627/0df7b7ca-f966-11e4-8958-761578537fc5.PNG)

**Comment by mac81** [comment]
Hi

Which version of Firefox do you use? And on what OS? 

I've not experienced any problems on Firefox

**Comment by brownprogrammer** [comment]
Windows 7 - Firefox 37.0.2 (latest version)

**Comment by mac81** [comment]
Strange. Everything looks fine on my end when I run it on Firefox. I have testet most versions on both OSX and Windows.

![screen shot 2015-05-13 at 21 54 15](https://cloud.githubusercontent.com/assets/254460/7619670/a373e180-f9ba-11e4-90f9-97ab14781603.png)
