### ISSUE TITLE
data-toggle="right"

### ISSUE THREAD

**Issue by mrbacay** [mac81/pure-drawer#16]
The value of the `right` CSS property compiles as `56/2px`

May I suggest to use something like these values on the following properties instead:
`left: 100%;`
`-webkit-transform: translateX(-110%);`
`transform: translateX(-110%);`

**Comment by mac81** [comment]
Hi

What compiler are you using? It compiles fine on my end. Compiles to 28px in the css.

**Comment by mrbacay** [comment]
I'm using Compass. What compiler should be used with it?

**Comment by mac81** [comment]
I've used libsass when developing pure drawer but it should work in all compilers. I will see if I can test it in compass and give you feedback on my findings

**Comment by mrbacay** [comment]
Thank you

**Comment by mac81** [comment]
I'm not getting the error in compass either, but you might want to try to wrap the divison i parentheses.

See line 150 in pure-drawer-global.scss

Change from: right: 56 / 2 + px to right: (56 / 2) + px

**Comment by mrbacay** [comment]
It worked. Thanks!

**Comment by mac81** [comment]
Excellent! I will update the source code accordingly incase others have the same issue. Thanks for reporting it in.
