### ISSUE TITLE
Screen stays grayed out when menu item is selected

### ISSUE THREAD

**Issue by nypraise** [mac81/pure-drawer#17]
When using the Pure-Drawer with AngularJS routing the content screen stays grayed out when an item on the menu is selected/pressed. Can this be set to normal automatic when an item in the menu is pressed?

**Comment by mac81** [comment]
Hi

You have to trigger a click on the 'pure-toggle-label' or 'pure-toggle' after routing to the new page.

**Comment by mac81** [comment]
Where you able to sort it out?

**Comment by nypraise** [comment]
I'm sorry I missed your reply, Mac81. What do mean trigger a click? How?

**Comment by mac81** [comment]
F.ex. with jQuery

$('.pure-toggle').trigger('click');

or native js

document.getElementsByClassName('.pure-toggle').click();

**Comment by nypraise** [comment]
Thank you! That solved it. :)

**Comment by LisaBee224** [comment]
Hi,

I'm having the same issue-- where do you put the trigger click, exactly? Is it just in a script at the end of the page? Sorry, I'm a noob!!

**Comment by nypraise** [comment]
Are you using Angular as well? If so; just use ng-click to call a function in the controller. Put the code inside the function. :)

**Comment by LisaBee224** [comment]
Sorry- I should have mentioned. I am not using Angular!

“Above all, do not lose your desire to walk: every day I walk myself into a
state of well-being and walk away from every illness; I have walked myself
into my best thoughts.” - Søren Kierkegaard

**Comment by mac81** [comment]
Just before the body tag should work fine. If you have a custom external script already it's best to put it there. If not either add a js file or just add it inline within a script tag.

If your looking to learn some javascript I would suggest looking at some free courses over at codeschool.com or http://code.tutsplus.com/categories/javascript
