### ISSUE TITLE
Scroll in Menu Div

### ISSUE THREAD

**Issue by pankajguptagkp** [mac81/pure-drawer#19]
i want to scroll down the menu section div. When items are overflow we can not see the items which are down side.

**Comment by mac81** [comment]
Hi

Thanks for testing out Pure Drawer.

Putting: 'overflow: auto' or 'overflow-y: auto' on the '.pure-drawer' should do the trick.

But note that this will insert a native scrollbar on the menu. If you want more control of the looks and functionality of the scrollbar a plugin like http://jscrollpane.kelvinluck.com/ will do the trick.
