### ISSUE TITLE
pure-container on the <body>

### ISSUE THREAD

**Issue by ottobyte** [mac81/pure-drawer#20]
Hi, thanks for this wonderful navigation, extremely useful.

Is there any reason I can't apply the pure-container class to the body of the page?

Thanks

**Comment by mac81** [comment]
Shouldn't be a problem applying pure-container to the body. Just make sure that you also include the data-effect attribute. Also because of the use of the general sibling selector the input, label, drawer and pure-pusher-container must be included directly inside the container.

**Comment by ottobyte** [comment]
Great, thanks. It seems to work so far. Yes I had a look in to understand how the drawer works, taught me about the sibling ~ selector - v clever:)

**Comment by mac81** [comment]
Thank you. Glad to be of help.
