### ISSUE TITLE
Nav menu doesn't show up in drawer

### ISSUE THREAD

**Issue by LisaBee224** [mac81/pure-drawer#21]
I'm using the slideAlong effect, and the contents of my nav menu (what goes in pure-drawer) don't show up-- they still have visibility:hidden when I expand the menu... any ideas???

**Comment by LisaBee224** [comment]
Ah, I found them-- they are just pushed way down on the page! I have to move them up. Not sure why this happened.

**Comment by mac81** [comment]
Glad you worked it out. I've not had that issue before. Maybe some other css messed it up?
