### ISSUE TITLE
Move toggler

### ISSUE THREAD

**Issue by nward85** [mac81/pure-drawer#22]
Is it possible to not have a fixed toggler? I want it positioned within my header/logo. Then an exit toggler within the menus...

**Comment by mac81** [comment]
It's possible. 

Just add two 'pure-toggle-label'

For example: 

<label class="pure-toggle-label pure-toggle-label-one" for="pure-toggle-left" data-toggle-label="left">
    <span class="pure-toggle-icon"></span>
</label> 

<label class="pure-toggle-label pure-toggle-label-two" for="pure-toggle-left" data-toggle-label="left">
    <span class="pure-toggle-icon"></span>
</label> 

and adjust the css for the pure-toggle-label
