### ISSUE TITLE
pure-pusher-container seems to create a overflow issue

### ISSUE THREAD

**Issue by nypraise** [mac81/pure-drawer#23]
Hi,

I have an AngularJS SPA and I seems to get an overflow problem when I manipulate the html inside the container from another html template that is bind to the DOM at a later time. (Popover with settings). 

One of the settings in the SPA is filtering a list and reduce the size of the container, at the same time it cuts the popover with the settings. I will attach image.

I have tried to make overflow:visible  and set a min-height on the pure-pusher-container, but it stills cut the popover.

Do you know of any way to prevent it form happening?
![overflow](https://cloud.githubusercontent.com/assets/3933998/9543553/f16ccbbe-4d79-11e5-92e1-445f5aeb4713.PNG)

**Comment by nypraise** [comment]
Sure. :)

Yeah, they are all height 100%.

**Comment by nypraise** [comment]
Did you manage to solve this, mac81?

**Comment by nypraise** [comment]
@mac81 Any progress on this issue?

**Comment by mac81** [comment]
@nypraise Sorry for extremely late answer . Haven't had time to look at it. Hard for me to reproduce the issue locally. Do you have a link to your project?
