### ISSUE TITLE
nav doesn't scroll with "pure-effect-fade" on IPad 

### ISSUE THREAD

**Issue by Harpie11** [mac81/pure-drawer#24]
Thank you for the great work.
I fell in love with "pure-effect-fade"..... but there is an error which I can not resolve.
With an IPAD I can not make a scrollable Navigation if I use my favorite  "pure-effect-fade"
If I use for example  "pure-effect-slide" it is working as expected

For any help, I am very grateful

**Comment by mac81** [comment]
![pure-video](https://cloud.githubusercontent.com/assets/254460/9686790/ebbd7d06-5325-11e5-8258-e32eea207203.gif)

**Comment by Harpie11** [comment]
Yes, I tried with      'overflow-y: auto'     to the 'pure-drawer' class
I tried even with       -webkit-overflow-scrolling: touch;    to the  'pure-drawer' class
But always the same problem with the   I PAD ... the navigation is not moving.

Again, this belongs to the 'fade-effect' only with --> I PAD

For example
The 'slide-effect' works perfect with -> 'overflow-y: auto'  on -> IPAD 

Both effects work with  -> 'overflow-y: auto'  <-  perfect.on  DESKTOP with mouse Scrolling.

Best Regards

**Comment by mac81** [comment]
@Harpie11 Sorry for late response. Were you able to sort this out or does the issue still apply?
