### ISSUE TITLE
Scroll with page?

### ISSUE THREAD

**Issue by samuelhwolfe** [mac81/pure-drawer#26]
Hi Thomas,

I'm having some trouble modifying the CSS to make the hamburger icon scroll with the page. It stays fixed at the top of my page regardless of my changes.

Thoughts?

**Comment by mac81** [comment]
Hi

Not sure if I understood you question. You want the hamburger icon to be positioned statically at the top of the page? Just as regular stuff,, so it disappears when you scroll?

**Comment by samuelhwolfe** [comment]
Correct. I want it to flow with the page instead of remaining fixed at the top.

**Comment by mac81** [comment]
Just move `<label class="pure-toggle-label" for="pure-toggle-left" data-toggle-label="left"><span class="pure-toggle-icon"></span></label>` inside `<div class="pure-pusher">` and set the position of `.pure-toggle-label` from 'fixed' to 'absolute'
