### ISSUE TITLE
Menu breaks parallax images

### ISSUE THREAD

**Issue by webact-tyler** [mac81/pure-drawer#33]
Thank you for the awesome nav code!

I am having a small issue where the expanded menu breaks the hero parallax background.

Example site: [https://www.webact.com/100/]

If you scroll halfway down the hero image, then open the menu, then scroll back up, the image no longer parallaxes and there's a large white space.  It only happens while the menu is open.  Any ideas why this is happening? 

I've in-lined all the CSS so you can see it in the page source.

Thanks!

**Comment by mac81** [comment]
Hi

Seems to be a repaint issue in Chrome. 

The issue is caused by this styling: 

`@media` (min-width: 1025px)
.hero {
    background-attachment: fixed;
}`

Adding `transform: translateZ(0);` to the .hero class should force a repaint. It is considered a hack and comes at the cost of some performance, but it should do the trick.

So to sum up this would be the correct styling

`@media` (min-width: 1025px)
.hero {
    background-attachment: fixed;
    transform: translateZ(0);
}`

Please let me know if this solves your issue.

**Comment by webact-tyler** [comment]
Hmm adding that stops the background from parallaxing in Chrome and Firefox.  Works perfectly in IE though.   I tried -webkit and -moz variations with the same results.  Any ideas?

Thank you for your help.

**Comment by mac81** [comment]
Hmm. I think I've figured it out. Can you try to change

`[data-effect='effect-reveal'] .toggle[data-toggle='left']:checked ~ .pusher-container .pusher {
    -webkit-transform: translate3d(300px,0,0);
    transform: translate3d(300px,0,0);
}`

into 

`[data-effect='effect-reveal'] .toggle[data-toggle='left']:checked ~ .pusher-container .pusher {
    -webkit-transform: translateX(300px);
   transform: translateX(300px);
}`

**Comment by webact-tyler** [comment]
That works, thank you!   FYI I had to remove the transform: translateZ(0); off the hero element first.  In Firefox only the it stops parallaxing while the menu is open, but I can deal with that.  Chrome and IE working perfect now.

Closing issue.

**Comment by mac81** [comment]
Excellent! Yup, the transform: translateZ(0); is no longer needed.

Happy coding!
