### ISSUE TITLE
preventing the "pure-pusher-container" contents to scroll up when clicked on the menu

### ISSUE THREAD

**Issue by halukkaramete** [mac81/pure-drawer#34]
Hi,

Is there a way to prevent to automaitically scrolling to the top? 
If the user happens to be in the middle of the page, and happens to click on the menu icon, the page he was on automatically scrolls all the way to the top.

I'd like a behaviour like that on cc.com. 

Is it possible to achieve this with this tool?

**Comment by mac81** [comment]
Not sure if i completely understand your question. If you scroll down the page and click the menu icon the page won't scroll with 'Pure Drawer'. It will of course scroll to top if you click on a link in the menu and load a new page.

Or am I missing something?

**Comment by halukkaramete** [comment]
You understood it correctly but it's my bad.

Your demo works.  The problem is in my implementation.
In my case, page does scroll to the top ( as soon as I click on the
hamburger icon )
But your demo works as it should be.

I've got to figure why mine is acting up like that.
Thank you anyway.
