### ISSUE TITLE
managing open / close state when main page is clicked to close the menu

### ISSUE THREAD

**Issue by halukkaramete** [mac81/pure-drawer#35]
When the hamburger menu content is longer than the actual main page content,  the menu content sticks out at the page's bottom area.

I manage the hiding and showing of that area by the following code, and it works

	$('#hamburger_menu_icon').click(function(){

		menu_open_now = !menu_open_now;   // on page load, menu_open_now is set as false
		
		if ( menu_open_now ){
			
			$('[data-effect="pure-effect-reveal"] .pure-drawer').attr('style', 'visibility:visible;overflow:scroll');					
			
		} else {
			$('[data-effect="pure-effect-reveal"] .pure-drawer').attr('style', 'visibility:hidden;overflow:hidden');					
		}	
	});

As you see the logic is simple, add the visibility and overflow styles properly at the proper time.

This code obviously fires ONLY WHEN the menu icon is clicked!
With every click on that icon, I reverse bool variable menu_open_now to keep track of the state.

However, since clicking on any dim area on the main page also closes the menu, there goes my tracking! 

How do I catch a click event on the main page ( while it is dim ) so I can update the state & run similar code as above?

**Comment by mac81** [comment]
You could just put an `overflow-y: scroll` on the `.pure-drawer` class.

Or you could listen to the toggle onchange event with javascript.

F.ex

`$('.pure-toggle').on('change', function(){

	var open = $(this).prop('checked');
	
	if(open) {	
		$('[data-effect="pure-effect-reveal"] .pure-drawer').attr('style', 'visibility:visible;overflow:scroll');						
	} else {
		$('[data-effect="pure-effect-reveal"] .pure-drawer').attr('style', 'visibility:hidden;overflow:hidden');					
	}	
});`
