### ISSUE TITLE
strategy to cut down on the large CSS file

### ISSUE THREAD

**Issue by halukkaramete** [mac81/pure-drawer#36]
Hello, the CSS file I downloaded has 9500+ lines and it's got all the effects and a lot of base styles which goes in conflict with existing theme.

There is also a big list of instructions on things like this
@keyframes bounceInUp {
@-webkit-keyframes bounceOut {
@keyframes bounceOut {
@-webkit-keyframes bounceOutDown {
@keyframes bounceOutDown {
@-webkit-keyframes bounceOutLeft {
...

What strategy would you recommend that I use to grab only the styles needed and perhaps bring the actual css needed down to less than 1000 lines? 

For example, I need only the reveal effect. 
Do I still need all those keyframes line and normalize.css, Animate.css  sections?

**Comment by mac81** [comment]
If you use the sass version you will have full control of what you want to include.

For vanilla css you will need to remove manually. 

But yes, you can remove all effects and animations for those you don't need
