### ISSUE TITLE
license please

### ISSUE THREAD

**Issue by destan** [mac81/pure-drawer#40]
I'd like to use this lib however couldn't find any license. So I can't use it. Please put a license to your library. My humble suggestion is [Mozilla Public License 2.0 (MPL-2.0)](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2))

**Comment by mac81** [comment]
Hi

It's licensed under https://opensource.org/licenses/MIT

It's mentioned on the demo page, but I've forgotten to put it in the repo. I'll remedy that shortly.

Thanks for trying out pure-drawer
