### ISSUE TITLE
menus are hiding in landscape mode as push-drawer isn't scrollable

### ISSUE THREAD

**Issue by CharlesKumar** [mac81/pure-drawer#47]
my issue may be similar to https://github.com/mac81/pure-drawer/issues/43

But my query is specific, the menu area is hiding when screen height is small

Any good suggestions to overcome this problem

**Comment by mac81** [comment]
Not completely sure what the problem is. Could you maybe send a screenshot or describe the issue further?

Regarding push-drawer not being scrollable I believe adding 'overflow: auto;' to the 'pure-drawer' will solve the issue.

**Comment by CharlesKumar** [comment]
![screen shot 2017-08-18 at 13 02 25](https://user-images.githubusercontent.com/14817903/29448713-957c4e36-8415-11e7-8219-1477ba932e29.png)

Some menus were hiding in smaller height screens

I set `overflow:scroll` to .pure-drawer wrapper 

`<div class="pure-drawer theme-light ovf-scr" data-position="left">`

Now it scrolls to show the hidden menus 

Note I am not sure if this is a right solution
