### ISSUE TITLE
Resize Icon?

### ISSUE THREAD

**Issue by bertmahoney** [mac81/pure-drawer#48]
Wondering how I can easily resize the menu icon and the 'close icon'?

I see in the source code how I might change the size of the circle around the icons, but not the icons themselves.

**Comment by mac81** [comment]
Sure. Just modify the .pure-toggle-icon, .pure-toggle-icon:before and .pure-toggle-icon:after

**Comment by bertmahoney** [comment]
Thanks, that helps.
One other question related to those three selectors.

I can adjust the width of the icon, but the height changes the 'thickness' of the lines. I need to reduce the height of the entire set of lines and keep the spacing proportional between them.

It seems as if margin/padding doesn’t work.

**Comment by mac81** [comment]
If you have a look at the :before and :after pseudo selectors you will see:
transform: translate3d(-50%, -14px, 0); and transform: translate3d(-50%, 10px, 0);

The second parameter controls the spacing between the lines. The first line is default -14px from the center and the third line 10px down from the center.

**Comment by bertmahoney** [comment]
That worked perfectly! Thanks so much for not only creating this, sharing it, but being willing to reply to my questions in figuring out how to make it work for my needs.
Cheers, Bert

**Comment by mac81** [comment]
Thank you! Glad to help.
