### ISSUE TITLE
Custom toggle?

### ISSUE THREAD

**Issue by timurridjanovic** [mac81/pure-drawer#49]
is there a way to control the toggling of the drawer with custom buttons? How would I trigger the opening and closing of the drawer if I dont want to use your built-in toggle icon.

**Comment by mac81** [comment]
Sure. Do you want to trigger it with javascript? Or just have another button that triggers the drawer?

**Comment by Stefdv** [comment]
Well. @timurridjanovic didn't respond so let me hijack the question. I try to use it together with [Bulma](https://bulma.io/) so i would need to trigger the drawer tru javascript. An thoughts on that ?

**Comment by mac81** [comment]
Hi Stefdv

Are you using vanilla js or some library like f.ex jQuery?

**Comment by Stefdv** [comment]
Hey 
Actually i use Vue ;p 
But i think i solved it.  
Just removed the label tag and use another way to set the 'checked' state on the input.
Tx for responding so quickly though 👍 
Really like 'pure-drawer'
