### ISSUE TITLE
Menu Toggler in Safari

### ISSUE THREAD

**Issue by arkitoure** [mac81/pure-drawer#8]
Good day Thomas, thank you for this wonderful drawer, an elegant and simple solution I must say! I did however discover a bit of a bug while doing some dev work on ios 7, OSX 10.9.5 Safari (just didn't check Safari on Windows) --- edit--- Windows too.

The drawer toggle shows in a distorted manner in static and morph states...even doing it on the Pure Drawer demo site. This only shows up in Safari and nothing else. I dug to see what the problem was and it might be a webkit issue or is there some tech that Safari has yet to get up to speed with? Any insight on this issue would be much appreciated as the ipad is natural habitat for this functionality. ;) Thank you for your time.

**Comment by arkitoure** [comment]
Thomas thank you for this update...sorry for the delay (enforced holiday break!)

It works perfectly and looks beautiful...we are working it into or project now and I will report back so you can see it in action. Thank you again.

**Comment by mac81** [comment]
No problem. Glad I could help :-)

Looking forward to seeing it in action!
